export const collections = [
  {
    id: 'raw-denim',
    title: 'Raw Denim Series',
    category: 'Denim',
    description: 'Unwashed, untreated, and pure. The foundation of authentic jeanswear.',
    longDescription: 'Our Raw Denim Series pays homage to the origins of denim. Woven on vintage shuttle looms, these fabrics feature a tight, irregular weave that develops a unique patina over time. Ideal for heritage brands and denim purists who value character and longevity.',
    features: ['100% Cotton', 'Selvedge Edge', 'Heavyweight (14oz+)', 'Sanforized & Unsanforized options'],
    image: 'https://picsum.photos/800/1000?random=1',
    images: [
      'https://picsum.photos/800/1000?random=1',
      'https://picsum.photos/800/1000?random=11',
      'https://picsum.photos/800/1000?random=12',
    ],
  },
  {
    id: 'sustainable-blends',
    title: 'Eco-Weave Blends',
    category: 'Sustainable',
    description: 'Organic cotton and recycled polyester blends for a sustainable future.',
    longDescription: 'The Eco-Weave collection represents our commitment to the planet. By blending GOTS-certified organic cotton with REPREVE® recycled polyester, we create fabrics that are soft, durable, and environmentally responsible. Perfect for modern, eco-conscious fashion lines.',
    features: ['GOTS Certified Organic Cotton', 'Recycled Polyester', 'Low-impact Dyes', 'Soft Handfeel'],
    image: 'https://picsum.photos/800/1000?random=2',
    images: [
      'https://picsum.photos/800/1000?random=2',
      'https://picsum.photos/800/1000?random=21',
      'https://picsum.photos/800/1000?random=22',
    ],
  },
  {
    id: 'stretch-tech',
    title: 'Performance Stretch',
    category: 'Performance',
    description: 'Advanced elasticity without compromising the authentic denim look.',
    longDescription: 'Engineered for movement, our Performance Stretch line utilizes dual-core spun yarns to provide superior recovery and comfort. These fabrics look like authentic rigid denim but feel like your favorite activewear, making them ideal for the modern urban lifestyle.',
    features: ['High Elasticity', 'Shape Retention', 'Breathable', 'Authentic Slub Character'],
    image: 'https://picsum.photos/800/1000?random=3',
    images: [
      'https://picsum.photos/800/1000?random=3',
      'https://picsum.photos/800/1000?random=31',
      'https://picsum.photos/800/1000?random=32',
    ],
  },
  {
    id: 'vintage-selvedge',
    title: 'Vintage Selvedge',
    category: 'Denim',
    description: 'Recreating the golden era of denim with authentic shuttle loom weaving.',
    longDescription: 'Woven on restored Toyoda shuttle looms, our Vintage Selvedge collection captures the essence of mid-century denim. The slow weaving process creates a fabric with rich texture and a distinctive "self-edge" that prevents unraveling. A true collector\'s choice.',
    features: ['Shuttle Loom Woven', 'Red/Blue ID', 'Rope Dyed Indigo', 'Natural irregularities'],
    image: 'https://picsum.photos/800/1000?random=4',
    images: [
      'https://picsum.photos/800/1000?random=4',
      'https://picsum.photos/800/1000?random=41',
      'https://picsum.photos/800/1000?random=42',
    ],
  },
  {
    id: 'linen-blend',
    title: 'Summer Linen',
    category: 'Lightweight',
    description: 'Breathable linen-cotton blends perfect for warmer climates.',
    longDescription: 'Our Summer Linen collection combines the breathability of flax with the softness of cotton. These lightweight fabrics feature a subtle slub texture and a crisp hand, making them perfect for summer shirting, dresses, and relaxed trousers.',
    features: ['Breathable', 'Natural Cooling', 'Textured Surface', 'Garment Dye Ready'],
    image: 'https://picsum.photos/800/1000?random=5',
    images: [
      'https://picsum.photos/800/1000?random=5',
      'https://picsum.photos/800/1000?random=51',
      'https://picsum.photos/800/1000?random=52',
    ],
  },
  {
    id: 'heavy-canvas',
    title: 'Industrial Canvas',
    category: 'Workwear',
    description: 'Rugged, durable canvas for workwear and accessories.',
    longDescription: 'Built to last, our Industrial Canvas is a heavyweight fabric designed for the toughest conditions. Tightly woven from 2-ply yarns, it offers exceptional abrasion resistance and water repellency. Ideal for jackets, bags, and utility pants.',
    features: ['Heavyweight (12-18oz)', 'Abrasion Resistant', 'Water Repellent Finish', 'Tight Weave'],
    image: 'https://picsum.photos/800/1000?random=6',
    images: [
      'https://picsum.photos/800/1000?random=6',
      'https://picsum.photos/800/1000?random=61',
      'https://picsum.photos/800/1000?random=62',
    ],
  },
];
